CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_ZBUS=y
CONFIG_LOG=y
CONFIG_UART_ASYNC_API=y
CONFIG_CAN=y
CONFIG_SHELL=y
CONFIG_SHELL_THREAD_PRIORITY_OVERRIDE=n
# CONFIG_SHELL_THREAD_PRIORITY=7
CONFIG_TIMESLICING=y
CONFIG_TIMESLICE_SIZE=1
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_PRINTK=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y
CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_MIN=y
CONFIG_DEBUG_COREDUMP_SHELL=y

CONFIG_CHERRYUSB=y
CONFIG_CHERRYUSB_DEVICE=y
CONFIG_CHERRYUSB_DEVICE_SPEED_AUTO=y
CONFIG_CHERRYUSB_DEVICE_HPM=y
CONFIG_CHERRYUSB_DEVICE_CDC_ACM=y

CONFIG_RM_TEST_RUNTIME_INIT_UART=y
CONFIG_RM_TEST_RUNTIME_INIT_USB=y
CONFIG_RM_TEST_RUNTIME_INIT_LITTLEFS=y
CONFIG_RM_TEST_SHELL_MAVLINK_CONTROL=y

# Keep shell/console on UART0 and business UART on UART1 without async IRQ conflicts.
CONFIG_UART_ASYNC_API=n
